c_stdlib:                  # [not unix]
  - m2w64-sysroot          # [not unix]
c_stdlib_version:
  - "10.13"                # [osx and x86_64]
  - "11.0"                 # [osx and arm64]
  - "2.28"                 # [linux]
  - "12"                   # [not unix]

c_compiler:                # [not linux]
  - clang                  # [not linux]
c_compiler_version:        # [not linux]
  - 18                     # [not linux]
cxx_compiler:              # [not linux]
  - clangxx                # [not linux]
cxx_compiler_version:      # [not linux]
  - 18                     # [not linux]
