# We cannot cross-compile a cross-compilers, thus not all combinations are activated.
ghc_target_arch:
  - x86_64-unknown-linux-gnu  # [linux64]
  - aarch64-unknown-linux-gnu  # [linux]
  # - powerpc64le-unknown-linux-gnu  # [linux64]
  - x86_64-apple-darwin13.4.0  # [osx]
  # - aarch64-apple-darwin  # [osx]
  - other  # [not unix]
conda_target_arch:
  - x86_64-conda-linux-gnu           # [linux64]
  - aarch64-conda-linux-gnu          # [linux]
  # - powerpc64le-conda-linux-gnu      # [linux64]
  - x86_64-apple-darwin13.4.0     # [osx]
  # - arm64-apple-darwin20.0.0      # [osx]
  - other  # [not unix]
ghc_target_platform:
  - linux-64  # [linux64]
  - linux-aarch64  # [linux]
  # - linux-ppc64le  # [linux64]
  - osx-64  # [osx]
  # - osx-arm64  # [osx]
  - other  # [not unix]
zip_keys:
  -
    - ghc_target_arch
    - conda_target_arch
    - ghc_target_platform
