{% set name = "ghc" %}
{% set version = "9.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-x86_64-apple-darwin.tar.bz2  # [osx]
    folder: binary  # [osx]
    sha256: 0a9a9a5499ffa8a7b7b3755088674c9e765281d35febff30a601de7277aa6d5d  # [osx]
  - url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-x86_64-rocky8-linux.tar.xz  # [build_platform == "linux-64"]
    folder: binary  # [build_platform == "linux-64"]
    sha256: 853909835ea9de6db39a0db0d52c01e7f200c816e925895199a1e62ad7c5901f  # [build_platform == "linux-64"]
  - url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-src.tar.xz
    folder: source
    sha256: bf386a302d4ee054791ffd51748900f15d71760fd199157922d120cc1f89e2f7

build:
  number: 0
  skip: true  # [not unix]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patchelf  # [linux]
    - gnuconfig
    - gmp
    - ncurses
    - perl
    - make
    - automake
    - autoconf
    - libtool
    - llvmdev 9.*  # [aarch64]
  host:
    - xz
    - gmp
    - ncurses
    - libffi
    - cffi
  run:
    - {{ c_compiler }}_{{ target_platform }} >={{ c_compiler_version }}
    - llvm-tools 9.*  # [aarch64]

test:
  files:
    - hello.hs
  commands:
    - ghc --help
    - ghc hello.hs -o hello

about:
  home: https://haskell.org/ghc/
  license: BSD-3-Clause
  license_family: BSD
  license_file: binary/LICENSE
  summary: Glorious Glasgow Haskell Compilation System

  doc_url: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/
  dev_url: https://github.com/ghc/ghc

extra:
  recipe-maintainers:
    - eggzilla
    - step21
    - xhochy
