{% set name = "ghc" %}
{% set version = "8.6.4" %}
{% set unixsha256 = "b18c0a39b0e3ae3f6a5ca79f078110bc95f52ff11d550bbcebd1479e727368e6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/ghc/ghc/archive/ghc-8.6.4-release.tar.gz #https://downloads.haskell.org/~{{name}}/{{ version }}/{{ name }}-{{ version }}-src.tar.xz  # [linux]
    sha256: {{ unixsha256 }}  # [linux]

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ghc-bootstrap
    - automake
    - autoconf
    - libtool
    - make
    - happy
    - alex
    - sphinx
  host:
    - xz
    - binutils  # [linux and c_compiler == 'toolchain_c' ]
    - gmp
    - ncurses
    - libffi

test:
  commands:
    - ghc --help

about:
  home: https://haskell.org/ghc/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Glorious Glasgow Haskell Compilation System'

  doc_url: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/
  dev_url: https://github.com/ghc/ghc

extra:
  recipe-maintainers:
    - eggzilla
