{% set name = "ghc" %}
{% set version = "8.2.2" %}
{% set unixsha256 = "cd7afbca54edf9890da9f432c63366556246c85c1198e40c99df5af01c555834" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://downloads.haskell.org/~{{ name }}/{{ version }}/{{ name }}-{{ version }}-x86_64-deb7-linux.tar.xz  # [linux]
    sha256: {{ unixsha256 }}  # [linux]

build:
  number: 1002
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - binutils_impl_linux-64  # [linux and c_compiler != 'toolchain_c' ]
    - binutils  # [linux and c_compiler == 'toolchain_c' ]
    - gmp
    - ncurses
  host:
    - xz
    - binutils_impl_linux-64  # [linux and c_compiler != 'toolchain_c' ]
    - binutils  # [linux and c_compiler == 'toolchain_c' ]
    - gmp
    - ncurses

test:
  commands:
    - ghc --help

about:
  home: https://haskell.org/ghc/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Glorious Glasgow Haskell Compilation System'

  doc_url: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/
  dev_url: https://github.com/ghc/ghc

extra:
  recipe-maintainers:
    - eggzilla
