{% set name = "ghc" %}
{% set version = "9.2.4" %}

{% if ghc_target_platform is undefined %}
{% set ghc_target_platform = "foo" %}
{% endif %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  - url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-x86_64-apple-darwin.tar.xz  # [osx]
    folder: binary  # [osx]
    sha256: f2e8366fd3754dd9388510792aba2d2abecb1c2f7f1e5555f6065c3c5e2ffec4  # [osx]
  - url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-x86_64-centos7-linux.tar.xz  # [build_platform == "linux-64"]
    folder: binary  # [build_platform == "linux-64"]
    sha256: 540d3a8ddcf6175efeeec54a73893526a6acf464825f7d3d7a396158fc3f6928  # [build_platform == "linux-64"]
  - url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-src.tar.xz
    folder: source
    sha256: 15213888064a0ec4e7723d075f31b87a678ce0851773d58b44ef7aa3de996458
    patches:
      - 0001-Use-CC_GHC_TARGET-in-gmp-build.patch

build:
  number: 1
  skip: true  # [not unix]

outputs:
  - name: ghc_{{ ghc_target_platform }}_{{ version }}
    script: build-compiler.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
{% if ghc_target_platform.startswith("linux") %}
        - gcc_{{ ghc_target_platform }}
        - gxx_{{ ghc_target_platform }}
{% elif ghc_target_platform.startswith("osx") %}
        - clang_{{ ghc_target_platform }}
        - clangxx_{{ ghc_target_platform }}
{% endif %}
        - patchelf  # [linux]
        - gnuconfig
        - gmp
        - ncurses
        - perl
        - make
        - automake
        - autoconf
        - libtool
        - llvmdev 11.*  # [osx]
        - llvmdev 12.*  # [linux]
        - sed
      host:
        - xz
        - gmp
        - ncurses
        - libffi
        - cffi
      run:
        - {{ c_compiler }}_{{ ghc_target_platform }} >={{ c_compiler_version }}
        - llvm-tools 11.*  # [osx]
        - llvm-tools 12.*  # [linux]
    test:
      files:
        - hello.hs
      commands:
        - echo {{ ghc_target_platform }}-{{ ghc_target_arch }}-{{ conda_target_arch }}
        - {{ conda_target_arch }}-ghc-{{ version }} --help
        - {{ conda_target_arch }}-ghc-{{ version }} hello.hs -o hello
  - name: ghc_{{ ghc_target_platform }}
    # We will build this in a a separate repository with the correct cross-compilation activation
    build:
      skip: true  # [ghc_target_platform != target_platform]
    script: build-compiler-links.sh
    requirements:
      host:
        - {{ pin_subpackage('ghc_' + ghc_target_platform + '_' + version, exact=True) }}
      run:
        - {{ pin_subpackage('ghc_' + ghc_target_platform + '_' + version, exact=True) }}
    test:
      files:
        - hello.hs
      commands:
        - echo {{ ghc_target_platform }}-{{ ghc_target_arch }}-{{ conda_target_arch }}
        - {{ conda_target_arch }}-ghc --help
        - {{ conda_target_arch }}-ghc hello.hs -o hello
  - name: ghc
    script: build-ghc.sh
    build:
      skip: true  # [ghc_target_platform != target_platform]
    requirements:
      host:
        - {{ pin_subpackage('ghc_' + ghc_target_platform, exact=True) }}
      run:
        - {{ pin_subpackage('ghc_' + ghc_target_platform, exact=True) }}
    test:
      files:
        - hello.hs
      commands:
        - echo {{ ghc_target_platform }}-{{ ghc_target_arch }}-{{ conda_target_arch }}
        - ghc hello.hs -o hello
        - ./hello

about:
  home: https://haskell.org/ghc/
  license: BSD-3-Clause
  license_family: BSD
  license_file: binary/LICENSE
  summary: Glorious Glasgow Haskell Compilation System

  doc_url: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/
  dev_url: https://github.com/ghc/ghc

extra:
  feedstock-name: ghc
  recipe-maintainers:
    - eggzilla
    - step21
    - xhochy
