{% set name = "ghc" %}
{% set version = "9.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-x86_64-apple-darwin.tar.xz  # [osx]
    folder: binary  # [osx]
    sha256: c527700a210306098ce85d2c956089deea539aefe1d1816701d5c14cf9c113b7  # [osx]
  - url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-x86_64-centos7-linux.tar.xz  # [build_platform == "linux-64"]
    folder: binary  # [build_platform == "linux-64"]
    sha256: 4b67324507f5d14c23db3ed83c57f4e25d877e97d2b93cfe8e1a9fdf65e4efa1  # [build_platform == "linux-64"]
  - url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-src.tar.xz
    folder: source
    sha256: f444012f97a136d9940f77cdff03fda48f9475e2ed0fec966c4d35c4df55f746

build:
  number: 0
  skip: true  # [not unix]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patchelf  # [linux]
    - gnuconfig
    - gmp
    - ncurses
    - perl
    - make
    - automake
    - autoconf
    - libtool
    - llvmdev 9.*  # [aarch64]
  host:
    - xz
    - gmp
    - ncurses
    - libffi
    - cffi
  run:
    - {{ c_compiler }}_{{ target_platform }} >={{ c_compiler_version }}
    - llvm-tools 9.*  # [aarch64]

test:
  files:
    - hello.hs
  commands:
    - ghc --help
    - ghc hello.hs -o hello

about:
  home: https://haskell.org/ghc/
  license: BSD-3-Clause
  license_family: BSD
  license_file: binary/LICENSE
  summary: Glorious Glasgow Haskell Compilation System

  doc_url: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/
  dev_url: https://github.com/ghc/ghc

extra:
  recipe-maintainers:
    - eggzilla
    - step21
    - xhochy
