{% set name = "ghc" %}
{% set version = "8.10.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-x86_64-apple-darwin.tar.xz  # [osx]
    folder: binary  # [osx]
    sha256: 287db0f9c338c9f53123bfa8731b0996803ee50f6ee847fe388092e5e5132047  # [osx]
  - url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-x86_64-centos7-linux.tar.xz  # [build_platform == "linux-64"]
    folder: binary  # [build_platform == "linux-64"]
    sha256: 262a50bfb5b7c8770e0d99f54d42e5876968da7bf93e2e4d6cfe397891a36d05  # [build_platform == "linux-64"]
  - url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-x86_64-unknown-mingw32.tar.xz   # [build_platform == "win-64"]
    folder: binary  # [build_platform == "win-64"]
    sha256: b6515b0ea3f7a6e34d92e7fcd0c1fef50d6030fe8f46883000185289a4b8ea9a  # [build_platform == "win-64"]
  - url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-src.tar.xz
    folder: source
    sha256: e3eef6229ce9908dfe1ea41436befb0455fefb1932559e860ad4c606b0d03c9d

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}      # [not win]
    - {{ compiler('cxx') }}    # [not win]
    - patchelf  # [linux]
    - gnuconfig  # [not win]
    - gmp  # [not win]
    - ncurses  # [not win]
    - perl  # [not win]
    - make  # [not win]
    - automake  # [not win]
    - autoconf  # [not win]
    - libtool  # [not win]
    - llvmdev 9.*  # [aarch64]

  host:
    - xz  # [not win]
    - gmp  # [not win]
    - ncurses  # [not win]
    - libffi  # [not win]
    - cffi  # [not win]
  run:
    - {{ c_compiler }}_{{ target_platform }} >={{ c_compiler_version }}  # [not win]
    - llvm-tools 9.*  # [aarch64]

test:
  files:
    - hello.hs
  commands:
    - ghc --help
    - ghc hello.hs -o hello

about:
  home: https://haskell.org/ghc/
  license: BSD-3-Clause
  license_family: BSD
  license_file: source/LICENSE
  summary: Glorious Glasgow Haskell Compilation System

  doc_url: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/
  dev_url: https://github.com/ghc/ghc

extra:
  recipe-maintainers:
    - eggzilla
    - step21
    - xhochy
