{% set name = "ghc" %}
{% set version = "8.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://downloads.haskell.org/~ghc/{{ version }}/ghc-{{ version }}-x86_64-fedora27-linux.tar.xz
    sha256: "8ab2befddc14d1434d0aad0c5d3c7e0c2b78ff84caa3429fa62527bfc6b86095"

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - xz
    - gmp
  host:
    - gmp
  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gmp

about:
  home: https://haskell.org/ghc/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Feedstock for Glorious Glasgow Haskell Compilation System'

  doc_url: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/
  dev_url: https://github.com/ghc/ghc

extra:
  recipe-maintainers:
    - eggzilla
