{% set name = "ghc" %}
{% set version = "9.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-x86_64-apple-darwin.tar.xz  # [osx]
    folder: binary  # [osx]
    sha256: 42f2d4e384a21956e806bcf8745ed436f799e5eca28839dfb81dd3dc7895ca41  # [osx]
  - url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-x86_64-centos7-linux.tar.xz  # [build_platform == "linux-64"]
    folder: binary  # [build_platform == "linux-64"]
    sha256: c2c9e171c205922a7c80e4b43e0432ebdb857076453f969dfda3ba9844aa5f5d  # [build_platform == "linux-64"]
  - url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-src.tar.xz
    folder: source
    sha256: 50ecdc2bef013e518f9a62a15245d7db0e4409d737c43b1cea7306fd82e1669e

build:
  number: 0
  skip: true  # [not unix]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patchelf  # [linux]
    - gnuconfig
    - gmp
    - ncurses
    - perl
    - make
    - automake
    - autoconf
    - libtool
    - llvmdev 9.*  # [aarch64]
  host:
    - xz
    - gmp
    - ncurses
    - libffi
    - cffi
  run:
    - {{ c_compiler }}_{{ target_platform }} >={{ c_compiler_version }}
    - llvm-tools 9.*  # [aarch64]

test:
  files:
    - hello.hs
  commands:
    - ghc --help
    - ghc hello.hs -o hello

about:
  home: https://haskell.org/ghc/
  license: BSD-3-Clause
  license_family: BSD
  license_file: binary/LICENSE
  summary: Glorious Glasgow Haskell Compilation System

  doc_url: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/
  dev_url: https://github.com/ghc/ghc

extra:
  recipe-maintainers:
    - eggzilla
    - step21
    - xhochy
