{% set name = "ghc" %}
{% set version = "9.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-x86_64-apple-darwin.tar.xz  # [osx]
    folder: binary  # [osx]
    sha256: eb78361feaf4277f627cbdc4b849849d09d175d0d878d28433719b7482db27f5  # [osx]
  - url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-x86_64-centos7-linux.tar.xz  # [build_platform == "linux-64"]
    folder: binary  # [build_platform == "linux-64"]
    sha256: 70c3ecbc6457f67ba0e76bd0ca2500bd0edd8262d3236a23422fad7602efa672  # [build_platform == "linux-64"]
  - url: https://downloads.haskell.org/~ghc/{{ version }}/{{ name }}-{{ version }}-src.tar.xz
    folder: source
    sha256: 5f13d1786bf4fd12f4b45faa37abedb5bb3f36d5e58f7da5307e8bfe88a567a1

build:
  number: 0
  skip: true  # [not unix]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - patchelf  # [linux]
    - gnuconfig
    - gmp
    - ncurses
    - perl
    - make
    - automake
    - autoconf
    - libtool
    - llvmdev 9.*  # [aarch64]
  host:
    - xz
    - gmp
    - ncurses
    - libffi
    - cffi
  run:
    - {{ c_compiler }}_{{ target_platform }} >={{ c_compiler_version }}
    - llvm-tools 9.*  # [aarch64]

test:
  files:
    - hello.hs
  commands:
    - ghc --help
    - ghc hello.hs -o hello

about:
  home: https://haskell.org/ghc/
  license: BSD-3-Clause
  license_family: BSD
  license_file: binary/LICENSE
  summary: Glorious Glasgow Haskell Compilation System

  doc_url: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/
  dev_url: https://github.com/ghc/ghc

extra:
  recipe-maintainers:
    - eggzilla
    - step21
    - xhochy
