{% set name = "ghc" %}
{% set version = "7.4.2" %}
{% set srchash = "f2ee1289a33cc70539287129841acc7eaf16112bb60c59b5a6ee91887bfd836d" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.haskell.org/~{{ name }}/{{ version }}/{{ name }}-{{ version }}-src.tar.bz2
  sha256: {{ srchash }}

build:
  number: 1003
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gmp
    - ncurses
    - perl
    - make  # [aarch64]
    - automake
    - autoconf
    - libffi
    - binutils_impl_{{ target_platform }}  # [linux]
  host:
    - xz
    - binutils_impl_{{ target_platform }}  # [linux]
    - gmp
    - libffi
    - ncurses

test:
  commands:
    - ghc --help

about:
  home: https://haskell.org/ghc/
  license: BSD-3-Clause 
  license_family: BSD
  license_file: LICENSE
  summary: 'Glorious Glasgow Haskell Compilation System'

  doc_url: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/
  dev_url: https://github.com/ghc/ghc

extra:
  recipe-maintainers:
    - eggzilla
    - step21
