context:
  version: "9.6.7"

package:
  name: ghc
  version: ${{ version }}

source:
  - url: https://downloads.haskell.org/~ghc/${{ version }}/ghc-${{ version }}-src.tar.xz
    sha256: d053bf6ce1d588a75cfe8c9316269486e9d8fb89dcdf6fd92836fa2e3df61305
    patches:
      - if: aarch64 or ppc64le or arm64
        then: patches/skip-bindist-recache-crosscompile.patch
      - if: not unix
        then:
          - patches/skip-mingw-copy-conda.patch
          - patches/force-system-gmp-windows.patch
          - patches/add-ffi-include-dir-substitution.patch
          - patches/fix-windows-thriomanager-include.patch
          - patches/add-threadlabels-include-consolehandler.patch
          - patches/fix-windows-utimbuf-type.patch
          - patches/disable-split-sections-windows.patch
          - patches/skip-mingw-detection-error.patch
          - patches/fix-windows-reportmemorymap-format.patch
          - patches/fix-windows-pei386-format.patch
          - patches/fix-windows-mmap-format.patch
          - patches/fix-hp2ps-utilities-stdlib.patch
      - if: osx and arm64
        then:
          - patches/patch-rpath-macos.patch
          - patches/patch-osname-macos.patch

build:
  number: 0
  skip: unix

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - binutils >=${{ binutils_version }}
    - if: target_platform != "linux-aarch64" and target_platform != "linux-ppc64le"
      then:
        - cabal ==3.10.3.0
        - ghc-bootstrap ==9.2.8
    - llvm-tools ${{ c_compiler_version }}.*
    - perl 5.32.*
    - pkg-config
    - python 3.10.*
    - sphinx

    - if: unix
      then:
        - autoconf
        - automake
        - file
        - m4
        - make
        - sed
      else:
        - libgcc-devel_win-64
        - m2-autoconf
        - m2-automake-wrapper
        - m2-bash
        - m2-coreutils
        - m2-file
        - m2-findutils
        - m2-grep
        - m2-m4
        - m2-make
        - m2-sed
        - m2-tar

    - if: build_platform != target_platform
      then:
        - gmp
        - libffi
        - libiconv
        - if: unix
          then: ncurses
  host:
    - gmp
    - libiconv
    - libffi
    - if: unix
      then: ncurses
  run:
    - if: unix
      then: ncurses
  ignore_run_exports:
    from_package:
      - ncurses
    
tests:
  - package_contents:
      bin:
        - ghc
        - ghc-pkg
        - ghci
        - hp2ps
        - hsc2hs
        - if: build_platform == target_platform
          then:
            - haddock
            - hpc
            - runghc
            - runhaskell
      files:
        - etc/bash_completion.d/ghc
        - etc/conda/activate.d/ghc_activate.sh
        - if: unix
          then:
            - lib/ghc-${{ version }}/lib/llvm-passes
            - lib/ghc-${{ version }}/lib/llvm-targets
            - lib/ghc-${{ version }}/lib/package.conf.d/**
            - lib/ghc-${{ version }}/lib/ghc-usage.txt
            - lib/ghc-${{ version }}/lib/ghci-usage.txt
            - lib/ghc-${{ version }}/lib/settings
            - lib/ghc-${{ version }}/lib/template-hsc.h
            - lib/ghc-${{ version }}/lib/*-ghc-${{ version }}/**
          else:
            - include/**
            - lib/bin/ghc-iserv.exe
            - lib/bin/touchy.exe
            - lib/bin/unlit.exe
            - lib/ghc-usage.txt
            - lib/ghci-usage.txt
            - lib/llvm-passes
            - lib/llvm-targets
            - lib/package.conf.d/**
            - lib/settings
            - lib/template-hsc.h
            - lib/x86_64-windows-ghc-${{ version }}/**

  - script: |
      ghc --version
      printf 'main = putStrLn "Hello conda-forge"\n' > hello.hs
      ghc -v hello.hs && ./hello
    requirements:
      run:
        - ${{ compiler('c') }}
        - libiconv
        - if: unix
          then: ${{ stdlib('c') }}
        - if: linux
          then: ld_impl_${{ target_platform }} ${{ binutils_version }}
        - if: osx or not unix
          then: lld

  - script:
      - if: not osx
        then:
          - printf 'main = putStrLn "Hello threaded conda-forge"\n' > hello_t.hs
          - ghc -threaded hello_t.hs && ./hello_t
          - printf 'main = putStrLn "Hello profiled conda-forge"\n' > hello_p.hs
          - ghc -v -prof hello_p.hs && ./hello_p
        else: echo "Profiling fails on osx"
    requirements:
      run:
        - ${{ compiler('c') }}
        - libiconv
        - if: unix
          then: ${{ stdlib('c') }}
        - if: linux
          then: ld_impl_${{ target_platform }} ${{ binutils_version }}

  - script: |
      printf 'main = putStrLn "Hello conda-forge"\n' > hello.hs
      ghc -dynamic hello.hs && ./hello
      printf 'main = putStrLn "Hello threaded conda-forge"\n' > hello_t.hs
      ghc -dynamic -threaded hello_t.hs && ./hello_t
    requirements:
      run:
        - ${{ compiler('c') }}
        - libiconv
        - if: unix
          then: ${{ stdlib('c') }}
        - if: linux
          then: ld_impl_${{ target_platform }} ${{ binutils_version }}
        - if: osx
          then: lld or not unix

  - script:
      - printf 'import System.Posix.Signals\nmain = installHandler sigTERM Default Nothing >> putStrLn "Signal test"\n' > signal_test.hs
      - if: unix
        then: |
          ghc signal_test.hs
          ./signal_test
        else: |
          echo Skipping signal test on Windows
    requirements:
      run:
        - ${{ compiler('c') }}
        - libiconv
        - if: unix
          then: ${{ stdlib('c') }}
        - if: linux
          then: ld_impl_${{ target_platform }} ${{ binutils_version }}
        - if: osx
          then: lld or not unix


about:
  homepage: https://haskell.org/ghc/
  license: BSD-3-Clause
  license_file:
    - LICENSE
  summary: Glorious Glasgow Haskell Compilation System
  description: |
    GHC is a state-of-the-art, open source, compiler and interactive environment 
    for the functional language Haskell.
  documentation: https://www.haskell.org/ghc/documentation.html
  repository: https://gitlab.haskell.org/ghc/ghc

extra:
  recipe-maintainers:
    - eggzilla
    - step21
    - xhochy
