compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
conda_forge_output_validation: true
provider: {linux_aarch64: default}
cuda_compiler_version:                    # [linux64]
  - None                                  # [linux64]
docker_image:                             # [linux64]
  - condaforge/linux-anvil-cos7-x86_64    # [linux64]
