# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-10.15
  strategy:
    matrix:
      osx_64_conda_target_archarm64-apple-darwin20.0.0ghc_target_archaarch64-apple-darwinghc_target_platformosx-arm64:
        CONFIG: osx_64_conda_target_archarm64-apple-darwin20.0.0ghc_target_archaarch64-apple-darwinghc_target_platformosx-arm64
        UPLOAD_PACKAGES: 'True'
      osx_64_conda_target_archx86_64-apple-darwin13.4.0ghc_target_archx86_64-apple-darwinghc_target_platformosx-64:
        CONFIG: osx_64_conda_target_archx86_64-apple-darwin13.4.0ghc_target_archx86_64-apple-darwinghc_target_platformosx-64
        UPLOAD_PACKAGES: 'True'
      osx_arm64_:
        CONFIG: osx_arm64_
        UPLOAD_PACKAGES: 'True'
  timeoutInMinutes: 360

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
        export IS_PR_BUILD="True"
      else
        export IS_PR_BUILD="False"
      fi
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)